name: Symfony

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

permissions:
  contents: write
  packages: write

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
        with:
          php-version: '8.2'
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Création du fichier .env.local et .env.test.local
        run: |
          touch .env.local
          touch .env.test.local
          echo "DATABASE_URL='sqlite:///%kernel.project_dir%/var/data.db'" >> .env.test.local
          echo "DATABASE_URL='sqlite:///%kernel.project_dir%/var/data.db'" >> .env.local
          echo "APP_SECRET='uneValeurParDefautPourLeCICD'" >> .env.local
          echo "APP_SECRET='uneValeurParDefautPourLeCICD'" >> .env.test.local
      - name: Suppression du fichier composer.lock
        run: rm composer.lock
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Installation des dépendances
        run: composer install
      - name: Création de la base de données
        run: php bin/console d:d:c --env=test
      - name: Ajout des fixtures aux dépendances
        run: composer require --dev orm-fixtures
      - name: Mise a jour du schéma de la base de données
        run: php bin/console d:s:u --force --env=test
      - name: Chargement des fixtures
        run: php bin/console d:f:l --env=test --no-interaction
      - name: Installation de tout ce qui concerne JavaScript
        run: npm install
      - name: Construction du dossier "public"
        run: npm run dev
      - name: Execution des tests
        env:
          DATABASE_URL: sqlite:///%kernel.project_dir%/var/data.db
        run: vendor/bin/phpunit